# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Spencer Folkman 
# Description of the Site
description: "Passionate about data science, driven by curiosity, and dedicated to turning data into actionable insights"
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: https://www.wsupercars.com/wallpapers-wide/Formula-1/McLaren/2023-Formula1-McLaren-MCL60-003-1440w.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mailto:sfolkman4@gmail.com
facebook_username: thedevslot
twitter_username: /
instagram_username: /
linkedin_username: https://www.linkedin.com/in/spencerfolkman
github_username: https://github.com/sfolkman4
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Spencer Folkman
# URL for the Image of the Author
author-image: /my-blog/assets/images/Logo.jpg
# 60 Words About the Author
author-about: Hi! I am Spencer Folkman, a passionate data scientist with a relentless curiosity for turning raw data into valuable insights. I am currently a student at Brigham Young Universtiy earning a B.S. in Statistics. Beyond the world of data, I'm a crypto enthusiast, podcast junkie, F1 fan, outdoorsman, and avid skier. Check out my blog to see some of the projects I have been working on!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/sfolkman4
#Quote
author-quote: "Without data, you're just another person with an opinion"

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
